name: CI

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Node.js 버전 설정

      - name: Install frontend dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Python 버전 설정

      - name: Install backend dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run backend tests
        run: |
          cd backend
          python -m unittest discover  # 유닛 테스트 실행 (테스트 파일 필요)

      - name: Run backend tests
        run: |
          cd backend
            flask run > output.log 2>&1 &
            sleep 5
            kill $!
